name: Deploy Worker (rtg-api)

on:
  push:
    branches: [ main ]
    paths:
      - "packages/worker/**"
      - ".github/workflows/deploy-worker.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Wrangler Action
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: packages/worker
          command: deploy