name: Deploy Worker (rtg-api)

on:
  push:
    branches: [ main ]
    paths:
      - "packages/worker/**"
      - ".github/workflows/deploy-worker.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler (global)
        run: npm i -g wrangler@3

      - name: Deploy Worker
        working-directory: packages/worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: wrangler deploy